# Site settings
email: "isaac.j.sant@gmail.com" 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-84586043-1

# SEO settings
title: isaacsant.com
description: 
url: "http://isaacsant.com"
twitter_username: isaacjsant
default_img: https://octodex.github.com/images/codercat.jpg

# Profile settings
name: Isaac sant
profile_img: https://octodex.github.com/images/codercat.jpg
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
